version: '3.9'

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./config/local.env
    environment:
      DSN: "postgres://postgres:123password@postgres:5432/books_shop?sslmode=disable"
    command: [ "bash", "/app/wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./app" ]

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123password
      POSTGRES_DB: books_shop
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
